spring.application.name=saludlink
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/saludlink_db
spring.datasource.username=postgres
spring.datasource.password=postnico
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Actuator
management.endpoints.web.exposure.include=health,info

# JWT
jwt.secret=saludlink-secret-key-2026-muy-segura
jwt.expiration=86400000
